### ISSUE TITLE
Cannot install current master branch

### ISSUE THREAD

**Issue by adover134** [scipopt/scip#106]
I tried to install SCIP with current master branch.
The environment is Ubuntu 20.04.6 LTS.
when I cmake then make, it showed error as this:
![Screenshot from 2024-09-05 15-29-02](https://github.com/user-attachments/assets/fedd2cb9-50de-488d-83cb-0fcd914b1f68)
I also tried `sudo apt-get install mklibs` to solve this, and the image above is an error still occurred after installed.

**Comment by svigerske** [comment]
The error message says that the MKL libs in some conda environment cannot be found. Maybe it was there but has been removed, but something like an Ipopt build still depends on it? Run SCIP's cmake with `-LA` to maybe get a clue where this dependency comes from.
