### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by adover134** [scipopt/scip#121]
I tried to install scip using all scipoptsuite libraries at once, using git repositories of each.

I did it by following order.
First, I downloaded the scipoptsuite tarball, then unzipped it.
Second, I removed each library folders from unzipped directory, then cloned recent version of each from git.
Third, then I used following code to cmake.
```
mkdir build
cd build
cmake ..
```
Fourth, cmake was successful, so I tried ```cmake test```, and it did not show any errors.

Then, finally, I tried ```make```, and I got following error.

```
[ 75%] Linking CXX executable ../../bin/scip
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libreadline.so: undefined reference to `tgoto@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libreadline.so: undefined reference to `UP@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libreadline.so: undefined reference to `tgetent@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libreadline.so: undefined reference to `tgetnum@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libreadline.so: undefined reference to `PC@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libreadline.so: undefined reference to `tgetstr@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libreadline.so: undefined reference to `tgetflag@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libreadline.so: undefined reference to `BC@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libreadline.so: undefined reference to `tputs@NCURSES6_TINFO_5.0.19991023'
collect2: error: ld returned 1 exit status
make[2]: *** [scip/src/CMakeFiles/scip.dir/build.make:6690: bin/scip] Error 1
make[1]: *** [CMakeFiles/Makefile2:2217: scip/src/CMakeFiles/scip.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

I found that one of closed issue suggested to install libreadline, so I tried to install with ```apt-get install libreadline8``` and ```apt-get install libreadline-dev```, but it says```libreadline8t64 is already the newest version (8.2-4build1).``` and ```libreadline-dev is already the newest version (8.2-4build1).```

What can be the solution for this problem? Should I install different version of libreadline? Then which version is available?

Edit:
I used Ubuntu 24.04.1 lts to install.

**Comment by adover134** [comment]
It seems I found something. This is result of ```apt-cache show libncurses6```.

```
Package: libncurses6
Architecture: amd64
Version: 6.4+20240113-1ubuntu2
Multi-Arch: same
Priority: standard
Section: libs
Source: ncurses
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Ncurses Maintainers <ncurses@packages.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 336
Depends: libtinfo6 (= 6.4+20240113-1ubuntu2), libc6 (>= 2.34)
Recommends: libgpm2
Breaks: cowdancer (<< 0.89~)
Filename: pool/main/n/ncurses/libncurses6_6.4+20240113-1ubuntu2_amd64.deb
Size: 111902
MD5sum: 183f2ef441248bda9ae14d35970c6adb
SHA1: 9d37d8e1151e6e30139dc994a392a6524d0c01fa
SHA256: f2b8efe3a3e2f622c5266d5a1301048306441885d2bbebc02685cb8c2d097537
SHA512: afc510b6e9503c2b2ad0df57bfe695832c0fdd586b74833d36fac3cfe323148da5d708b6a396595c0cd3d85770b6357b271e271383a0fb7080411d064e6e724e
Homepage: https://invisible-island.net/ncurses/
Description: shared libraries for terminal handling
Description-md5: 599cbbcff16d09b3b4643d84f37643fd
Task: standard
```

It seems the log requires libtinfo5, but the recent Ubuntu supports only libtinfo6.

**Comment by svigerske** [comment]
Maybe try uninstalling all readline packages and then install only `libreadline-dev`.

**Comment by adover134** [comment]
@svigerske, I found a solution from old issue with pretty different name. (I mean, it was a bit hard to find for me...)

https://github.com/neuronsimulator/nrn/issues/410#issuecomment-684399699

Now it is working.

**Comment by adover134** [comment]
@svigerske, I found a solution from old issue with pretty different name. (I mean, it was a bit hard to find for me...)

https://github.com/neuronsimulator/nrn/issues/410#issuecomment-684399699

Now it is working.

**Comment by adover134** [comment]
I just wanted to add one more thing. Sometimes, also need to use ```conda remove libgfortran```.

**Comment by adover134** [comment]
There was one more problem. We also remove libgfortran and its series(?)

**Comment by adover134** [comment]
I wrote on the other issue that mentioned this.
