### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by zengqg** [scipopt/scip#13]
* scip-8.0.0

make install
output :

//usr/local/lib/libreadline.so.8: undefined reference to `tgetstr'
//usr/local/lib/libreadline.so.8: undefined reference to `tputs'
//usr/local/lib/libreadline.so.8: undefined reference to `BC'
//usr/local/lib/libreadline.so.8: undefined reference to `tgetent'
//usr/local/lib/libreadline.so.8: undefined reference to `tgetflag'
//usr/local/lib/libreadline.so.8: undefined reference to `tgoto'
//usr/local/lib/libreadline.so.8: undefined reference to `UP'
//usr/local/lib/libreadline.so.8: undefined reference to `tgetnum'
//usr/local/lib/libreadline.so.8: undefined reference to `PC'
collect2: error: ld returned 1 exit status
gcg/src/CMakeFiles/gcg.dir/build.make:2211: recipe for target 'bin/gcg' failed
make[2]: *** [bin/gcg] Error 1
CMakeFiles/Makefile2:2954: recipe for target 'gcg/src/CMakeFiles/gcg.dir/all' failed
make[1]: *** [gcg/src/CMakeFiles/gcg.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fschloesser** [comment]
Dear @Domceng,
can you install the package `libreadline8` and try again please? 
Best,
Franziska
