### ISSUE TITLE
Linux ARM64 Binary Support

### ISSUE THREAD

**Issue by alexcaoys** [scipopt/scip#17]
Hi there, 

I was wondering if there will be an arm64/aarch64 binary of SCIP. I have used SCIP across all different platform (Windows, Linux x86_64, arm32). But currently run into some problem on Ubuntu arm64 (on a Raspberry Pi 4B). I have tried the Raspberry Pi binary but apparently it needs some kernel support to run arm32 binary. 

It will be great if you will release aarch64 binary in the future.

Thanks!

**Comment by alexcaoys** [comment]
> Hi, I have Radxa Zero similar to raspberry pi has ARM CPU. I was able to compile SCIP on both Debian and Manjaro. I dont think no need to kernel support. On [Download](https://www.scipopt.org/index.php#download) page SCIPopt Suite has Raspberry option. Alternatively you can compile on your own. I prefer compiling by myself because self compiled IPOPT has HSL solvers that makes significant speed improvements.

Hi there,

Thanks for your advices!

As I stated above, I have already tried the armv7 or armhf raspberry pi release. It will give me a `No such file or directory` error which suggested mismatched arch. ([Details here](https://askubuntu.com/questions/133389/no-such-file-or-directory-but-the-file-exists))

Yes, I can compile it on my own. It's just a better option that I can get it right away. I am mainly a Python user so I'd rather not go in depth with those compiler or kernel errors. lol

Thanks for your suggestion anyway!

**Comment by fschloesser** [comment]
Dear @alexcaoys,
For the time being we don't build arm64 binaries, but might in the future. Just check the download section on the scip download page. Thanks for letting us know you are interested! 
Best,
Franziska
