### ISSUE TITLE
Installation (CMake) Error

### ISSUE THREAD

**Issue by chemrgineer** [scipopt/scip#19]
I downloaded last version of SCIP from git repo. I compiled without any error. But I get this error massage when try to install with "sudo make install":

```
fatal: unsafe repository ('/home/radxa/Downloads/scip' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /home/radxa/Downloads/scip
CMake Error at scip_update_githash.cmake:12 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.


make[2]: *** [CMakeFiles/scip_update_githash.dir/build.make:70: CMakeFiles/scip_update_githash] Error 1
make[1]: *** [CMakeFiles/Makefile2:719: CMakeFiles/scip_update_githash.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```
I tried to add safe directory but nothing changed. I'm working on ARM architecture Radxa Zero.(cmake 3.23.1, Make 4.3)

**Comment by fschloesser** [comment]
Dear @chemrgineer 
I modified the CMakeLists.txt, can you please try again and in case it does not work, please attach the file that it complains about?
Best,
Franziska

**Comment by chemrgineer** [comment]
Hi @fschloesser, I compiled SCIP on Ubuntu 22.04 LTS (WSL) without any problem. I couldn't repeated process on ARM platform. Because I tried to compile Soplex first but I get same error (compiling but not able to install system). Thank you for fast response.
