### ISSUE TITLE
SCIP 8 concurrentopt

### ISSUE THREAD

**Issue by chemrgineer** [scipopt/scip#20]
Hi, I'm trying to use concurrentopt mode in SCIP. I compiled with CPLEX and IPOPT. While configuring with CMake I activated OpenMP library. So there is no problem with functionality. But my problem is working with Pyomo. Pyomo can not use internal functions as far as I know. I checked "scip --help" command and there is "-c "command"  : execute single line of dialog commands (can be used multiple times)". So that I decided to pass "-c concurrentopt" but its not working. 
I tried "scip -c concurrentopt -f example.nl" command and I get: "cannot mix batch mode '-c' and '-b' with file mode '-f'"
Is there any other alternatives to run parallel in default?

**Comment by fschloesser** [comment]
Hey @chemrgineer, 
Scip tells you what the problem is, you cannot mix batch mode with file mode. Try reading the instance in batch mode: `./scip -c "read example.nl concurrentopt"`
Best,
Franziska
