### ISSUE TITLE
When SoPlex is built with the MPFR option SCIP also begins to depend on libmpfr.so

### ISSUE THREAD

**Issue by yurivict** [scipopt/scip#3]

**Comment by fschloesser** [comment]
Can you please explain in more detail what the problem is here?

**Comment by yurivict** [comment]
When the dependency library (SoPlex) is optionally depending on the third library (libmpfr.so) this shouldn't cause your project to also immediately link with this third library.

**Comment by fschloesser** [comment]
> immediately link with this third library

What is the szenario and what command do you use for this to happen? Do you mean that this is automatically linked or that the binaries depend on a shared lib instead of using the static lib for the build process?

**Comment by svigerske** [comment]
No answer from submitter and not sure what the exact problem is.
