### ISSUE TITLE
Remove a node from node pool

### ISSUE THREAD

**Issue by dxyzx0** [scipopt/scip#33]
I have 2 questions:
1. Is it possible to remove a node from the node pool during the solving process safely? I want to remove a subtree from the solving process.
2. If so, is it possible to do that in fscip? Since fscip is a parallel version of scip, should I use some mutex/lock to accomplish this?

Thanks.

**Comment by ambros-gleixner** [comment]
1. Yes, absolutely, the UG framework does that, e.g., if you want to look at code to achieve it.
2. I suppose you mean remove "UG nodes". I guess so, but for that I would refer you to inquire at ug@zib.de. This would also be the best place to ask about 1.

**Comment by dxyzx0** [comment]
@ambros-gleixner Thanks, is there a proper way to ask questions about ug framework except via e-mail?

**Comment by dxyzx0** [comment]
> 1. Yes, absolutely, the UG framework does that, e.g., if you want to look at code to achieve it.
> 2. I suppose you mean remove "UG nodes". I guess so, but for that I would refer you to inquire at [ug@zib.de](mailto:ug@zib.de). This would also be the best place to ask about 1.

Yes, I want to accomplish things similar to UG framework. The code of UG is too long to read and has limited doc.
I have 2 additional questions:
1. What's the difference between UG node and scip node?
2. Is it possible to directly achieve this functionality just in scip? I mean, at some point, I can safely remove the node without destroy the solving process.

**Comment by ambros-gleixner** [comment]
To enquire about UG the mail ug@zib.de is the point of contact, or you can write to Yuji Shinano directly, same thing.  He would be the most competent person to answer your questions.  You can certainly achieve this safely within SCIP, e.g., by updating the lower bound to +infinity.
