### ISSUE TITLE
How to use SoPlex as an exact LP solver from SCIP?

### ISSUE THREAD

**Issue by msh086** [scipopt/scip#34]
Hi, I need to solve numerically difficult LP problems, and would like to use SoPlex as an exact LP solver from SCIP. In order to use SoPlex in exact mode, I need to set some parameters(e.g. setting both `feastol` and `opttol` to $0$ ) according to https://soplex.zib.de/doc/html/EXACT.php

However, I can't find a way to set the params in SCIP. In https://scipopt.org/doc/html/PARAMETERS.php, I can only find `numerics/feastol` and the minimal allowed value is $1e-17$.

Is there a way to set the SoPlex parameters through SCIP to make it solve in exact mode? Thank you for any help

**Comment by ambros-gleixner** [comment]
Through standard floating SCIP in current release versions, this is not possible.

If you want an exact LP solve, you need to either use SoPlex directly, or you can check out the exact version of SCIP at https://github.com/leoneifler/exact-SCIP. However, note that the second option has some restrictions: it may not be as efficient, you will not have access to tweek parameters for the exact algorithm used in SoPlex, and you will not get a dual solution.

**Comment by ambros-gleixner** [comment]
Please reopen for further questions, possibly also in the other repos.
