### ISSUE TITLE
Apache license availability: What is the release schedule for SCIP 8.0.3?

### ISSUE THREAD

**Issue by wkschwartz** [scipopt/scip#35]
I am very excited to use [SCIP v8.0.3 under the Apache 2 license](https://scipopt.org/index.php#license) in a commercial product. When do you expect to schedule 8.0.3's release? I am asking so that I can plan around it in upcoming releases of my software.

If this is a question [better directed](https://scipopt.org/doc/html/FAQ.php#licensefaq) to koch@zib.de, please let me know.

**Comment by fschloesser** [comment]
The release will hopefully take place in the coming month.
