### ISSUE TITLE
Debian packaging woes

### ISSUE THREAD

**Issue by WPettersson** [scipopt/scip#44]
I've just tried to install SCIPOptSuite-8.0.3-Linux-debian.deb on a Debian machine, and I'm getting conflicts with the [bliss](https://packages.debian.org/stable/main/bliss) package as both scipoptsuite and bliss want to install /usr/bin/bliss. I tried to find out how the debian package is actually built, but couldn't find any specific build script for creating the Debian package.

I do realise that SCIPOptSuite needs bliss 0.77, while debian stable (bullseye) and testing (bookworm) both only have bliss 0.73 available, so making SCIPOptSuite installable on debian stable is going to need some sort of internal bliss build (and possibly the same for other libraries), but would it be possible to create debian packages that won't have file collisions with other debian packages? I'm happy to attempt to make a build script for this if there is interest.

**Comment by Urquh4rt** [comment]
It is indeed not intended that bliss is installed anywhere by the SCIPOptSuite. The bliss library is built and linked statically from within SCIP and should be removed after linking. I am looking into this.

**Comment by WPettersson** [comment]
Not sure where the debian packaging scripts are located, but the 8.0.4 debian file depends on libgsl25 which is not a part of debian stable since bookworm became stable (libgsl25 is in bullseye / oldstable). Instead, libgsl27 is a part of bookworm / stable.

**Comment by svigerske** [comment]
bliss is not included with SCIP Optimization Suite 9.1.0, and so it shouldn't be installed anymore.

Further, I hope the libgsl dependency has disappeared. I see a change by @ju-manns that removed libgsl-dev from the docker images that are used to build the deb files.
