### ISSUE TITLE
Is is possible to access all rows in SCIP, including those that are not in the current LP?

### ISSUE THREAD

**Issue by SelinBayramoglu** [scipopt/scip#45]
Hello,

I am looking for a way to get all rows including those that are not in the current LP. I know that SCIPgetLPRows() returns the rows in the current LP but I also need those that are not in the current LP. I did not see a function that does this, so I was wondering if there is another way to achieve this? Thanks!

**Comment by antoniach** [comment]
Hi Selin,

I suppose this already got answered with Issue #46 ?

Best,
Antonia

**Comment by matbesancon** [comment]
closing for now if this has been answered
