### ISSUE TITLE
CI: Automatically build precompiled packages for every release

### ISSUE THREAD

**Issue by mmghannam** [scipopt/scip#55]
Add a github action to build the SCIP Optimization Suite for different operating systems with the latest version of SCIP. It should be triggered when a tag is added.

**Comment by svigerske** [comment]
We have Jenkins jobs and a GitLab pipeline that builds the SCIP Optimization Suite for any new tag. The binaries for releases are made available at www.scipopt.org and attached to releases of SCIP at GitHub.
I see no need to redo the same thing with GitHub actions.
