### ISSUE TITLE
How to interface SCIP using C-like functions

### ISSUE THREAD

**Issue by SanPen** [scipopt/scip#58]
Hello, 

I am writing a software that uses MIP solvers interchangeably and I would like to include SCIP as an option.

I have been looking for an example of how to build a problem and run it without much luck.

The [documentation](https://www.scipopt.org/doc/html/MIPSOLVER_MAIN.php) points nowhere, and the [MIP example](https://github.com/scipopt/scip/blob/master/examples/MIPSolver/src/cppmain.cpp) is about reading files. Not exactly what I need.

To be precise:

I would like to pass all the problem information by memory using C-style functions since I need to link scip dynamically.

An example of what I need, but using Highs is [this](https://github.com/ERGO-Code/HiGHS/blob/master/src/interfaces/highs_c_api.h).

**Any help figuring how to interface SCIP from C is appreciated.**

**Comment by SanPen** [comment]
I see that vars and constraints are added one by one.

Is it possible to pass the coefficients matrix by directly filling the internal sparse structure?

**Comment by ambros-gleixner** [comment]
No, see #56 .

**Comment by ambros-gleixner** [comment]
Please feel free to reopen if you have any further concrete questions.
