### ISSUE TITLE
Getting Full Search Tree

### ISSUE THREAD

**Issue by izuwaa** [scipopt/scip#6]
Hello Team,

I apologize if this is not the best place to post this request for help; having spent a few days trying to read documentation and figure out what to do. I need to get the entire search tree used during computation of a solution to an LP. This tree I assume would have unexplored nodes, pruned nodes etc. Is this possible on SCIP? Thanks for your help and guidance. 

I compiled SCIP 7.0.3 on Mac and I am coding on C++.

**Comment by leoneifler** [comment]
Hello, you are saying you want the search tree during the solution of an LP, is that a typo? A pure LP (no integer variables) does not require a tree search. If you mean MIP, how exactly do you want to have the tree? There exists, e.g. a visualization feature that writes the tree info to a file.

**Comment by izuwaa** [comment]
Hello,

Thank you for the speedy response. I did mean MIP apologies for that. I tried the visualization feature (visual/vbcfilename = "tree.vbc", visual/realtime = TRUE) the solution I got in the .vbc file seems to be the optimal solutions only plus I don't think the vbc output file is exactly what I am looking for. 

After the full search tree is generated, I want to be able to perform further calculations on a node that was pruned but near optimal; so I would ideally like to be able to iterate over output of the full search tree, know the total number of nodes, sort through them and perform computation on them.

I hope this provides some more clarity on what I am trying to do.

Thanks a lot for helping.

**Comment by izuwaa** [comment]
Any help with the above will be really appreciated.

Thanks,
Izuwa.

**Comment by leoneifler** [comment]
So if I understand you correctly you want to be able to access information for each of the nodes after (or during?) the solving of a MIP? I think this you would probably have to implement for yourself within SCIP. You could, for example create an event handler (https://www.scipopt.org/doc/html/EVENTHDLR_MAIN.php) that activates whenever a node is solved and either saves the information that you want in some data structure (in case you want to do this stuff during the tree search), or that writes the information to some file for you to access later.

**Comment by izuwaa** [comment]
Yes I would like to access the information of each node after the solving of an MIP. Thank you very much for pointing in the right direction. I would explore the event hander as recommended. 

I didn't want to recreate this if it was already in SCIP i.e. to query the search tree for solutions within x% of the optimal, and get those solutions and their associated values.

**Comment by leoneifler** [comment]
So some more info on this: If you only want to have as many solutions as possible, then you should definitly use an event that triggers on a found solution (`SCIP_EVENTTYPE_SOLFOUND`). Also: SCIP will of course not explore all feasible solutions (especially if you find an optimal solution early on, large parts of the tree might be pruned where suboptimal solutions could be found).

**Comment by izuwaa** [comment]
Ok. Thanks for this extra information. I would explore it.
