### ISSUE TITLE
Tag for v8.0.4

### ISSUE THREAD

**Issue by ldr709** [scipopt/scip#60]
I see from your [news page](https://www.scipopt.org/index.php#news) that  	SCIP 8.0.4 has been released, but there is no corresponding [tag](https://github.com/scipopt/scip/tags) here on this mirror. Could you please add a tag to indicate which commit corresponds to 8.0.4?

**Comment by matbesancon** [comment]
Hi, yes indeed it is missing. Sadly the tagging process on github is still manual and the people looking at it are on vacation

**Comment by lperron** [comment]
any news ? I would like to push the version for OR-Tools

**Comment by ju-manns** [comment]
We had an issue with a wrongly placed tag. We corrected this and the v804 tag is now on github.
