### ISSUE TITLE
Issue with numpy after installing pyscipopt with anaconda

### ISSUE THREAD

**Issue by ChrisMLikesMath** [scipopt/scip#64]
I've noticed this numpy issue after installing pyscipopt using conda and recreated it across multiple python versions (3.7-3.11) and PCs.

After conda installing pyscipopt, multiplying large numpy matrices causes python to crash. Empirically it looks like it starts when the matrix size gets beyond 2500x2500.

Steps to reproduce

> conda create -n myenv python=3.9 anaconda

Then running python and trying the following

> import numpy as np
> np.random.randn(3000,3000) @ np.random.randn(3000,3000)

This successfully returns a result.

After installing pyscipopt, however

> conda install -c conda-forge pyscipopt

the same multiplication above crashes python. For smaller matrix sizes, it's ok. Has anyone else encountered this?

**Comment by ambros-gleixner** [comment]
Hi! Can you move this issue to https://github.com/scipopt/pyscipopt ?
