### ISSUE TITLE
Coloring application Branching Rule contradictory code 

### ISSUE THREAD

**Issue by meffertj** [scipopt/scip#77]
Hello, 

The coloring branch and price application documentation says it selects the "most" fractional variable (both in the doc and in the  branch_coloring.c itself) but in the actual code it selects the "least" fractional variable, even stating so in the comment:

https://github.com/scipopt/scip/blob/6d9a5d4b96030945e8f620bf03887a59e0bd31a9/applications/Coloring/src/branch_coloring.c#L141

**Comment by meffertj** [comment]
I could do a pull request editing the mentioned code segment to indeed select the most fractional node

**Comment by ambros-gleixner** [comment]
Yes, that would be wonderful.  Thank you for noticing!

If you wanted to then you could even introduce a parameter to be able to switch between most and least fractional. But I believe that least fractional leads to better performance in practice.

**Comment by meffertj** [comment]
Alright, I changed the section in my fork. 
https://github.com/meffertj/scip_vcp_mostfractional/blob/master/applications/Coloring/src/branch_coloring.c

Do you have a recommendation as to what the most elegant place to introduce that parameter would be?

**Comment by ambros-gleixner** [comment]
Yes, the include method of the branching rule would be the natural place to do so, see https://github.com/meffertj/scip_vcp_mostfractional/blob/master/src/scip/branch_pscost.c#L777 for one example.

**Comment by ambros-gleixner** [comment]
A character parameter from the string "ml" might be a natural choice.

**Comment by leoneifler** [comment]
Is there any progress on this?

**Comment by meffertj** [comment]
I‘ve implemented it. My windows machine died, have since been working on my mac and was not able to test it yet

**Comment by meffertj** [comment]
I've fixed one error, now all tests run successfully. I am not sure if it is justified to add myself as an author to the file, depending on your approval I can do a pull request

**Comment by ambros-gleixner** [comment]
Great, thank you very much! It is absolutely good to add you as an author. I have transferred your branch to the internal repo where we merge and run the CI. @GioniMexi will be in contact with you regarding this!

**Comment by ambros-gleixner** [comment]
Your code has been merged and should be available on the master branch now. Can you confirm and close the comment if all looks good? Thank you again for your contribution!

**Comment by meffertj** [comment]
Looks good, thank you!
