### ISSUE TITLE
Highs interface, option values function call deprecated

### ISSUE THREAD

**Issue by Cellophil** [scipopt/scip#89]
I'm trying to compile scip 9.0 with highs as LP solver; I'm getting errors with both 

- highs 1.7: problems with getDoubleOptionValues
- highs 1.4: apparently zeroAllClocks could not be found

Highs.h defines getOptionValues and getDoubleOptionValues (mentioning that that is to be deprecated). lip_highs.cpp within the scip project only calls getOptionValues. Not sure where the issue is.

**Comment by svigerske** [comment]
lpi_highs.cpp uses `Highs::getOptionValue()`, but not `getDoubleOptionValues`.
I have no problems to compile the SCIP/HiGHS interface of SCIP 9.1.0 with HiGHS 1.7.1 (or SCIP 9.0.1 with HiGHS 1.7.0).

Please post what errors exactly you get with current SCIP and HiGHS, if there is still an issue.

**Comment by svigerske** [comment]
Closing this as no response.
