### ISSUE TITLE
Can't subscribe to the SCIP mailing list

### ISSUE THREAD

**Issue by AlexeyNikonorov** [scipopt/scip#94]
I'd like to subscribe to the [mailing list](http://listserv.zib.de/mailman/listinfo/scip/). I have a question to ask and github issue template says that the mailing list is the right place to it.

I filled out the form in the [mailing list](http://listserv.zib.de/mailman/listinfo/scip/) but didn't receive any response to my email in more than a month. I tried one more time but with the same result.

**Comment by antoniach** [comment]
Hi Alexey,

I am sorry for the inconvenience. Unfortunately, I don't know what went wrong; I am not able to see any subscription request from you. If you send me an email (chmiela@zib.de) with the email-address you want to use to subscribe to the mailing list, I can subscribe you directly. 


Best,
Antonia
