### ISSUE TITLE
Documentation update about trigonometric functions (cos, sin) support

### ISSUE THREAD

**Issue by pierre-haessig** [scipopt/scip#98]
Hello,

Base on the Julia/JuMP forum discussion [Can SCIP solve MINLP with trigonometric functions?](https://discourse.julialang.org/t/can-scip-solve-minlp-with-trigonometric-functions/116967), SCIP supports nonlinear expressions with trigonometric functions (cos, sin) as of 2024 (clearly stated in [SCIP.jl's README](https://github.com/scipopt/SCIP.jl/blob/master/README.md)).

However, the [SCIP 9.1.0 Documentation: Frequently Asked Questions (FAQ)](https://scipopt.org/doc-9.1.0/html/FAQ.php#minlptypes) sections says the opposite (*"Trigonometric functions are not yet supported by SCIP. "*). I guess it's outdated. I didn't find the release announcement ([git blame `src/scip/expr_trig.h`](https://github.com/scipopt/scip/blame/8beff14dc9380dbee60c7f86af9fc58927a13308/src/scip/expr_trig.h) points to changes made in 2020-2021 and https://github.com/scipopt/CSIP/issues/40 states that in 2018 it didn't), but you probably know better.

I don't know if the file [doc/inc/faq/faqtext.txt](https://github.com/scipopt/scip/blob/8beff14dc9380dbee60c7f86af9fc58927a13308/doc/inc/faq/faqtext.txt) is autogenerated or not. If not, I can submit a PR (I'm asking because last week, on another project, I wasted a PR by editing a autogenerated doc...).

Once the doc is updated (or just having a link to relevant release notes), the following OR Stackexchange question could be edited:
- https://or.stackexchange.com/questions/120/what-global-minlp-solvers-support-trigonometric-functions

**Comment by svigerske** [comment]
Indeed, this was added in SCIP 8.0.0, https://github.com/scipopt/scip/blob/4508ae71bf9a75ca2cc41b18616e647443c94d2a/CHANGELOG#L947

I can do the edits in the FAQ. Thank you.

**Comment by pierre-haessig** [comment]
Thanks for the reference. Now I found sin and cos mentioned in:
- SCIP 8.0.0 release notes https://scipopt.org/doc-8.0.0/html/RN80.php (in "Expressions" section)
- in the SCIP 8.0 paper https://optimization-online.org/2021/12/8728/ (in Section 4 SCIP’s New MINLP Framework / 4.1 New Expressions Framework)

**Comment by pierre-haessig** [comment]
I saw you commented on https://or.stackexchange.com/questions/120/what-global-minlp-solvers-support-trigonometric-functions, thanks.

I also did it on https://stackoverflow.com/questions/77788277/solve-minlp-with-scip, because although it's off topic regarding the question, it contains a well indexed copy of the SCIP FAQ with the outdated statement on trigonometric functions.
